config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :offers

  resources :articles
  resources :profiles

  devise_for :users, :skip => [:registration], controllers: {
    sessions: 'users/sessions'
  }

  get '/welcome/index'
  get '/welcome/who_are_we' => 'welcome#who_are_we'
  get '/welcome/innovate_together' => 'welcome#innovate_together'
  get '/welcome/job_theque' => 'welcome#job_theque'

  get '/admin/batch_processing' => 'admin#batch_processing'
  post '/admin/batch_processing' => 'admin#batch_processing'
  get '/admin/frontpage' => 'admin#frontpage'
  post '/admin/frontpage' => 'admin#frontpage'
  get '/admin/add_user' => 'admin#add_user'
  post '/admin/add_user' => 'admin#add_user'

  %w( 400 404 418 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { check_ownership(@article.user) }, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @articles = Article.all
    respond_with(@articles)
  end

  def show
    @comments = Comment.where(article: params[:id])
    respond_with(@article)
  end

  def new
    @article = Article.new
    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @article.save
    respond_with(@article)
  end

  def update
    if (@article.user == current_user or current_user.admin?) and @article.update(article_params)
      flash[:success] = 'Article mis à jour.'
    else
      flash[:error] = 'Une erreur est survenue lors de l\'édition de l\'article.'
    end
    respond_with(@article)
  end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:content, :title, :subtitle, :picture)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.erb
Rédiger un article<span class="slash_color_rose"> /</span><p></p>

<%= form_for(@article, url: article_path(@article)) do |f| %>
  <div class="details_article">
    <div class="img_article"><%= image_tag @article.picture || 'logo_identifiant.png', class: 'article_img' %></div>

    <div class="details_cadre">
      <div class="details_redaction">
        <div>
          <strong>Titre : </strong><br><br>
          <strong>Sous-titre :</strong><br><br>
          <strong>Lien vers l'image :</strong>
        </div>
        <div class="input_article">
          <%= f.text_field :title %><br><br>
          <%= f.text_field :subtitle %><br><br>
          <%= f.text_field :picture %>
        </div>
      </div>
    </div>
  </div>

  <div class="descript_article">
    <strong>Contenu de l'article :</strong></br></br>
    <%= f.text_area(:content, rows: 30, class: 'redaction_article') %>
    <div class="soumettre_article">
      <div class="bouton_soumettre_article">
        <%= f.submit 'Soumettre l\'article', class: 'bouton text_bouton' %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.erb
Articles<span class="slash_color_blue"> /</span><p></p>
<div class="block_line_filter">
  <div class="bouton_tous_membres"><a class="bouton" href="#"><p class="text_bouton">Tous nos articles</p></a></div>
  <div class="espace"></div>
  <div class="text_filtre"><p class="text_bouton">Filtrer par</p></div>
</div>
<div class="tableau_case">
  <% @articles.each_with_index do |article, index| %>
    <% if index.modulo(4) == 0 %><div class="line_case"><% end %>
      <div class="case" style="background-position: center; background-image: url('<%= article.picture || (asset_url 'logo_identifiant.png') %>')">
        <div class="color-article<%= rand(1..3) %>"></div>
        <%= link_to({action: 'show', id: article.id}, class: 'bouton2') do %>
          <div class="espace_icon_article">
          </div>
          <div class="titre_article"><%= article.title %></br><%= article.subtitle %><p><%= article.description %></p></div>
        <% end %>
      </div>
    <% if index.modulo(4) == 3 %></div><% end %>
  <% end %>
  <% (4 - @articles.size).abs.modulo(4).times do %>
    <div class="case">
      <div class="color-article<%= rand(1..3) %>"></div>
      <a class="bouton" href="#">
      </a>
    </div>
  <% end %>
  <% if @articles.size.modulo(3) != 2 %></div><% end %>
</div>

app/views/articles/index.html.haml
%h1 Articles

%table
  %thead
    %tr
      %th Titre
      %th Description
      %th Contenu
      %th Auteur
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.description
        %td= article.content
        %td= link_to article.user.fullname, profile_path(article.user.id)
        %td= link_to 'Show', article
        - if article.user == current_user or current_user.admin?
          %td= link_to 'Edit', edit_article_path(article)
          %td= link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Voulez-vous vraiment supprimer cet article ?' }

%br

- if user_signed_in?
  = link_to 'New Article', new_article_path

app/views/articles/new.html.erb
Écrire un article<span class="slash_color_rose"> /</span><p></p>

<%= form_for(@article, url: '/articles') do |f| %>
  <div class="details_article">
    <div class="img_article"><%= image_tag 'logo_identifiant.png', class: 'article_img' %></div>

    <div class="details_cadre">
      <div class="details_redaction">
        <div>
          <strong>Titre : </strong><br><br>
          <strong>Sous-titre :</strong><br><br>
          <strong>Lien vers l'image :</strong>
        </div>
        <div class="input_article">
          <%= f.text_field :title %><br><br>
          <%= f.text_field :subtitle %><br><br>
          <%= f.text_field :picture %>
        </div>
      </div>
    </div>
  </div>

  <div class="descript_article">
    <strong>Contenu de l'article :</strong></br></br>
    <%= f.text_area(:content, rows: 30, class: 'redaction_article') %>
    <div class="soumettre_article">
      <div class="bouton_soumettre_article">
        <%= f.submit 'Soumettre l\'article', class: 'bouton text_bouton' %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.erb
Articles<span class="slash_color_blue"> /</span><p></p>
<div class="details_article">
  <div class="img_article"><%= image_tag @article.picture || 'logo_identifiant.png', class: 'article_img' %></div>

  <div class="details">
    <p>
    <%= @article.created_at.strftime('%d/%m/%Y') %><br><br>
    <strong><%= @article.title %></strong><br>
    <em><%= @article.subtitle %></em></br>
      <div class="partage_article">
        <div class="text_partage">Partager cet article</div>
        <div class="logo_partage"><a class="bouton" href="https://www.facebook.com/sharer/sharer.php?u=<%= URI.encode(request.original_url) %>"><%= image_tag 'logo_fb.png', class: 'logo_part' %></a></div>
        <div class="logo_partage"><a class="bouton" href="https://www.linkedin.com/shareArticle?mini=true&url=<%= URI.encode(request.original_url) %>&title=<%= URI.encode(@article.title) %>&summary=<%= URI.encode(@article.subtitle) %>&source="><%= image_tag 'logo_lk.png', class: 'logo_part' %></a></div>
        <div class="logo_partage"><a class="bouton" href="https://www.twitter.com/share?text=<%= URI.encode(@article.title) %>"><%= image_tag 'logo_twitter.png', class: 'logo_part' %></a></div>
      </div>
    </p>
  </div>

  <div class="auteur_article">
    <div class="line_auteur">
      <div class="nom_auteur">Rédigé par <%= @article.user.firstname + " " + @article.user.lastname %></div><div class="img_auteur"><%= image_tag @article.user.gravatar_url, class: 'auteur_img' %></div>
    </div>
  </div>

</div>
<div class="descript_article">
  <%=raw RedCloth.new(@article.content || '').to_html %>
</div>
<% if can_edit_item?(@article) %>
<div class="ajouter_commentaire">
  <div class="bouton_ajouter_commentaire">
    <%= link_to({action: 'edit'}, {class: 'bouton'}) do %>
      <p class="text_bouton">Éditer cet article</p>
    <% end %>
  </div>
</div>
<div class="ajouter_commentaire">
  <div class="bouton_ajouter_commentaire">
    <%= link_to(article_path(@article), method: :delete, data: { confirm: 'Êtes-vous certain de vouloir supprimer cet article ?' }, class: 'bouton') do %>
      <p class="text_bouton">Supprimer cet article</p>
    <% end %>
  </div>
</div>
<% end %>

<% if user_signed_in? %>
<div class="commentaire_article">
  Mettre votre commentaire</br></br>
  <textarea class="votre_commentaire"rows="5"></textarea>
  <div class="ajouter_commentaire">
    <div class="bouton_ajouter_commentaire"><a class="bouton" href="#"><p class="text_bouton">Ajouter un commentaire</p></a></div>
  </div>
</div>
<% end %>

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Description:
  = @article.description
%p
  %b Content:
  = @article.content

%h2 Commentaires

- if @comments.size == 0
  %p Aucun commentaire.
- else
  %dl
    - @comments.each do |comment|
      %dt= comment.user.fullname + ", le " + comment.updated_on.to_formatted_s(:long_ordinal)
      %dd= comment.content

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path