config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :offers

  resources :articles
  resources :profiles

  devise_for :users, :skip => [:registration], controllers: {
    sessions: 'users/sessions'
  }

  get '/welcome/index'
  get '/welcome/who_are_we' => 'welcome#who_are_we'
  get '/welcome/innovate_together' => 'welcome#innovate_together'
  get '/welcome/job_theque' => 'welcome#job_theque'

  get '/admin/batch_processing' => 'admin#batch_processing'
  post '/admin/batch_processing' => 'admin#batch_processing'
  get '/admin/frontpage' => 'admin#frontpage'
  post '/admin/frontpage' => 'admin#frontpage'
  get '/admin/add_user' => 'admin#add_user'
  post '/admin/add_user' => 'admin#add_user'

  %w( 400 404 418 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  root 'welcome#index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user

  before_validation(on: :create) do
    if offer_type >= 0 and offer_type <= 2
      self.offer_type = offer_type
    else
      false
    end
  end

  def internship?
    (offer_type == 0)
  end

  def job?
    (offer_type == 1)
  end

  def pit?
    (offer_type == 2)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action -> { check_ownership(@offer.user) }, only: [:edit, :create, :update, :destroy]

  respond_to :html

  def index
    @offers = Offer.all
    @admin = (current_user and current_user.admin?)
    
    respond_with(@offers)
  end

  def show
    respond_with(@offer)
  end

  def new
    @offer = Offer.new
    respond_with(@offer)
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    @offer.save
    respond_with(@offer)
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer)
  end

  def destroy
    @offer.destroy
    respond_with(@offer)
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:offer_type, :user_id, :company, :title, :content, :date_from, :date_to)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
  def offer_type(offer_type)
    case offer_type
    when 0
      "stage"
    when 1
      "emploi"
    when 2
      "PIT"
    end
  end
end

app/views/offers/_form.html.haml
= form_for @offer do |f|
  - if @offer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@offer.errors.count, "error")} prohibited this offer from being saved:"
      %ul
        - @offer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :offer_type
    %select
      - (0..2).each do |i|
        = content_tag(:option, offer_type(i), value: i)
  .field
    = f.label :company
    = f.text_field :company
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :date_from
    = f.date_select :date_from
  .field
    = f.label :date_to
    = f.date_select :date_to
  .actions
    = f.submit 'Save'

app/views/offers/edit.html.haml
%h1 Editing offer

= render 'form'

= link_to 'Show', @offer
\|
= link_to 'Back', offers_path

app/views/offers/index.html.haml
%h1 Offres

%table
  %thead
    %tr
      %th Proposé par
      %th Type
      %th Entreprise
      %th Intitulé
      %th De
      %th À
      %th
      %th
      %th

  %tbody
    - @offers.each do |offer|
      %tr
        %td= offer.user.fullname
        %td= offer_type(offer.offer_type)
        %td= offer.company
        %td= offer.title
        %td= offer.date_from
        %td= offer.date_to
        %td= link_to 'Voir', offer
        - if offer.user == current_user or @admin
          %td= link_to 'Modifier', edit_offer_path(offer)
          %td= link_to 'Supprimer', offer, :method => :delete, :data => { :confirm => 'Êtes-vous sûr ?' }
        - else
          %td
          %td

%br

= link_to 'Nouvelle offre', new_offer_path

app/views/offers/new.html.haml
%h1 New offer

= render 'form'

= link_to 'Back', offers_path

app/views/offers/show.html.haml
%p#notice= notice

%p
  %b Type:
  = offer_type(@offer.offer_type)
%p
  %b User:
  = @offer.user.fullname
%p
  %b Company:
  = @offer.company
%p
  %b Titre:
  = @offer.title
%p
  %b Content:
  = @offer.content
%p
  %b Date from:
  = @offer.date_from
%p
  %b Date to:
  = @offer.date_to
%p
  %b Created on:
  = @offer.created_on
%p
  %b Updated on:
  = @offer.updated_on

= link_to 'Edit', edit_offer_path(@offer)
\|
= link_to 'Back', offers_path